# POTGRES DB
version: '3.1'

services:

  node:
    image: node-docker
    restart: unless-stopped
    ports:
      - 8001:8001

  flask:
    image: flask-docker
    restart: unless-stopped
    ports:
      - 8002:8002

  php:
    image: php-docker
    restart: unless-stopped
    ports:
      - 8003:80

  db:
    image: postgres
    restart: unless-stopped
    environment:
      # POSTGRES_PASSWORD: uEA7t8ReFUa8E8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8010:8080
  
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://postgres:secret@db:5432/testdb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - db