insert into todos (user_id, todo) values (998, 'Sertraline');
insert into todos (user_id, todo) values (440, 'APCAL');
insert into todos (user_id, todo) values (336, 'NITROUS OXIDE');
insert into todos (user_id, todo) values (380, 'Halobetasol Propionate');
insert into todos (user_id, todo) values (20, 'Whole System EEP');
insert into todos (user_id, todo) values (327, 'Clear');
insert into todos (user_id, todo) values (69, 'Bacitracin');
insert into todos (user_id, todo) values (921, 'Docusate Sodium');
insert into todos (user_id, todo) values (611, 'Amoxicillin');
insert into todos (user_id, todo) values (503, 'Sertraline Hydrochloride');
insert into todos (user_id, todo) values (482, 'Treatment Set TS331567');
insert into todos (user_id, todo) values (58, 'Fluconazole');
insert into todos (user_id, todo) values (933, 'Nabumetone');
insert into todos (user_id, todo) values (288, 'Oil-Free Foaming Acne Wash');
insert into todos (user_id, todo) values (298, 'Bisacodyl');
insert into todos (user_id, todo) values (438, 'Allergy Relief');
insert into todos (user_id, todo) values (29, 'Isopropyl Alcohol');
insert into todos (user_id, todo) values (532, 'Torsemide');
insert into todos (user_id, todo) values (317, 'RITE AID RENEWAL');
insert into todos (user_id, todo) values (637, 'ACD-A');
insert into todos (user_id, todo) values (59, 'Gemfibrozil');
insert into todos (user_id, todo) values (366, 'MAGNESIA PHOSPHORICA');
insert into todos (user_id, todo) values (307, 'Jafra');
insert into todos (user_id, todo) values (200, 'Irinotecan Hydrochloride');
insert into todos (user_id, todo) values (280, 'Equaline Ibuprofen');
insert into todos (user_id, todo) values (788, 'Animal Allergens, AP Dog Hair and Dander Canis spp');
insert into todos (user_id, todo) values (513, 'HyQvia');
insert into todos (user_id, todo) values (684, 'Antifungal');
insert into todos (user_id, todo) values (784, 'VITAMIN D');
insert into todos (user_id, todo) values (387, 'Icee White Cherry Scented Hand Sanitizer');
insert into todos (user_id, todo) values (559, 'NIA 24 SPF 30');
insert into todos (user_id, todo) values (655, 'Amoebatox');
insert into todos (user_id, todo) values (919, 'Diltiazem Hydrochloride');
insert into todos (user_id, todo) values (311, 'Breacold Children');
insert into todos (user_id, todo) values (257, 'BETTER THAN NATURE ESSENCE');
insert into todos (user_id, todo) values (104, 'Benztropine Mesylate');
insert into todos (user_id, todo) values (506, 'Alcohol Prep Pad');
insert into todos (user_id, todo) values (438, 'EX-LAX');
insert into todos (user_id, todo) values (934, 'HUSKY 505 Antiseptic Cleanser');
insert into todos (user_id, todo) values (177, 'Acne Solution');
insert into todos (user_id, todo) values (767, 'BeneFIX');
insert into todos (user_id, todo) values (617, 'Hypericum Bryophyllum');
insert into todos (user_id, todo) values (817, 'JAKAFI');
insert into todos (user_id, todo) values (704, 'Aunt Bees Five Flavors');
insert into todos (user_id, todo) values (654, 'Pramipexole dihydrochloride');
insert into todos (user_id, todo) values (755, 'Mi Acid');
insert into todos (user_id, todo) values (192, 'Hydrocortisone Maximum Strength with Aloe');
insert into todos (user_id, todo) values (626, 'Low Sugar Cherry Flavor Fishermans Friend Menthol Cough Suppressant');
insert into todos (user_id, todo) values (354, 'ARRID XX Roll On');
insert into todos (user_id, todo) values (273, 'Mucinex DM');
insert into todos (user_id, todo) values (693, 'Mucinex Sinus-Max');
insert into todos (user_id, todo) values (305, 'Kroger Medicated Wipes');
insert into todos (user_id, todo) values (930, 'Good Sense Nasal');
insert into todos (user_id, todo) values (707, 'Lunesta');
insert into todos (user_id, todo) values (835, 'Gadavyt');
insert into todos (user_id, todo) values (929, 'Sulwhasoo');
insert into todos (user_id, todo) values (581, 'Clindamax');
insert into todos (user_id, todo) values (417, 'Cabergoline');
insert into todos (user_id, todo) values (117, 'Good Neighbor Pharmacy Nicotine');
insert into todos (user_id, todo) values (774, 'Fluocinonide');
insert into todos (user_id, todo) values (828, 'Omeprazole');
insert into todos (user_id, todo) values (293, 'Standardized Mite D. farinae');
insert into todos (user_id, todo) values (403, 'HOMATROPINE HYDROBROMIDE OPHTHALMIC');
insert into todos (user_id, todo) values (506, 'Naproxen');
insert into todos (user_id, todo) values (826, 'Epirubicin Hydrochloride');
insert into todos (user_id, todo) values (403, 'Cephalexin');
insert into todos (user_id, todo) values (737, 'Nicotrol (Professional Sample)');
insert into todos (user_id, todo) values (918, 'Givenchy TEINT COUTURE Long Wearing Fluid Foundation with Sunscreen Broad Spectrum SPF 20 ELEGANT PORCELAIN');
insert into todos (user_id, todo) values (760, 'LBel');
insert into todos (user_id, todo) values (502, 'Oxycodone and Acetaminophen');
insert into todos (user_id, todo) values (618, 'Norco');
insert into todos (user_id, todo) values (849, 'Trimethobenzamide Hydrochloride');
insert into todos (user_id, todo) values (994, 'Gaviscon');
insert into todos (user_id, todo) values (991, 'Oxcarbazepine');
insert into todos (user_id, todo) values (889, 'LOBSTER');
insert into todos (user_id, todo) values (317, 'Mirtazapine');
insert into todos (user_id, todo) values (762, 'Kogenate FS');
insert into todos (user_id, todo) values (533, 'Zostrix Foot Pain Relief');
insert into todos (user_id, todo) values (484, 'Trospium Chloride');
insert into todos (user_id, todo) values (611, 'Arnica Echinacea First Aid');
insert into todos (user_id, todo) values (824, 'Thyrolar');
insert into todos (user_id, todo) values (887, 'Didanosine');
insert into todos (user_id, todo) values (130, 'Valacyclovir hydrochloride');
insert into todos (user_id, todo) values (421, 'Ibuprofen');
insert into todos (user_id, todo) values (615, 'Treatment Set TS333938');
insert into todos (user_id, todo) values (336, 'Intervene Makeup SPF 15 Soft Cocoa');
insert into todos (user_id, todo) values (840, 'Stratuscare Milk of Magnesia Cherry');
insert into todos (user_id, todo) values (3, 'SULWHASOO EVENFAIR PERFECTING CUSHION NO.25');
insert into todos (user_id, todo) values (2, 'Fluconazole');
insert into todos (user_id, todo) values (924, 'Sulwhasoo');
insert into todos (user_id, todo) values (382, 'Ampicillin and Sulbactam');
insert into todos (user_id, todo) values (294, 'Liver comp. Special Order');
insert into todos (user_id, todo) values (389, 'Terrasil Anti-Fungal Treatment');
insert into todos (user_id, todo) values (202, 'Oxygen');
insert into todos (user_id, todo) values (957, 'Gabapentin');
insert into todos (user_id, todo) values (633, 'Kidney Bladder Support');
insert into todos (user_id, todo) values (989, 'PRIME PRIMER HYDRATING');
insert into todos (user_id, todo) values (362, 'LAMISIL');
insert into todos (user_id, todo) values (975, 'ESIKA');
insert into todos (user_id, todo) values (767, 'Justice');
insert into todos (user_id, todo) values (248, 'Robitussin Maximum Strength Cough Plus Chest Congestion DM');
insert into todos (user_id, todo) values (439, 'HOUSE DUST');
insert into todos (user_id, todo) values (227, 'Lidocaine Hydrochloride');
insert into todos (user_id, todo) values (822, 'Sumatriptan');
insert into todos (user_id, todo) values (20, 'Sei Bella Skin Refining Tinted Moisturizer');
insert into todos (user_id, todo) values (773, 'CEDAX');
insert into todos (user_id, todo) values (630, 'Optimal Diet Plan');
insert into todos (user_id, todo) values (382, 'Citalopram');
insert into todos (user_id, todo) values (464, 'Trazodone Hydrochloride');
insert into todos (user_id, todo) values (525, 'Gabapentin');
insert into todos (user_id, todo) values (794, 'Ranitidine');
insert into todos (user_id, todo) values (596, 'Enalapril Maleate');
insert into todos (user_id, todo) values (30, 'Banana Boat Sport Performance');
insert into todos (user_id, todo) values (750, 'Severe Oral Pain Reliever');
insert into todos (user_id, todo) values (854, 'Loratadineantihistamine');
insert into todos (user_id, todo) values (351, 'dg health night time cold and flu relief');
insert into todos (user_id, todo) values (967, 'venlafaxine');
insert into todos (user_id, todo) values (724, 'Anti-Diarrheal');
insert into todos (user_id, todo) values (421, 'CLE DE PEAU BEAUTE FOUNDATION L');
insert into todos (user_id, todo) values (346, 'ANTIBACTERIAL FOAMING');
insert into todos (user_id, todo) values (266, 'Boudreauxs');
insert into todos (user_id, todo) values (520, 'MOZI-Q');
insert into todos (user_id, todo) values (119, 'Bald Cypress');
insert into todos (user_id, todo) values (481, 'Thyroid Assist');
insert into todos (user_id, todo) values (321, 'Loratadine Allergy Relief');
insert into todos (user_id, todo) values (425, 'Temazepam');
insert into todos (user_id, todo) values (825, 'Lisinopril');
insert into todos (user_id, todo) values (406, 'LAMICTAL');
insert into todos (user_id, todo) values (847, 'Bacitracin Zinc and Polymyxin B Sulfate');
insert into todos (user_id, todo) values (542, 'Clolar');
insert into todos (user_id, todo) values (729, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (753, 'Smart Sense Allergy and Congestion Relief-D');
insert into todos (user_id, todo) values (948, 'Caldesene Baby');
insert into todos (user_id, todo) values (53, 'Epoch');
insert into todos (user_id, todo) values (610, 'BEXXAR');
insert into todos (user_id, todo) values (615, 'METFORMIN HYDROCHLORIDE');
insert into todos (user_id, todo) values (188, 'Softlips Pure Tint');
insert into todos (user_id, todo) values (127, 'CENTER-AL - ALNUS INCANA SSP. RUGOSA POLLEN');
insert into todos (user_id, todo) values (458, 'Jane Seymour Natural Advantage');
insert into todos (user_id, todo) values (553, 'clear days ahead');
insert into todos (user_id, todo) values (957, 'Amoxicillin');
insert into todos (user_id, todo) values (797, 'Cepacol');
insert into todos (user_id, todo) values (600, 'cold and flu relief');
insert into todos (user_id, todo) values (37, 'DOK EXTRA STRENGTH STOOL SOFTENER');
insert into todos (user_id, todo) values (938, 'Isocaine');
insert into todos (user_id, todo) values (653, 'Tamsulosin Hydrochloride');
insert into todos (user_id, todo) values (478, 'Verapamil Hydrochloride');
insert into todos (user_id, todo) values (883, 'Cedar X Formula');
insert into todos (user_id, todo) values (899, 'Assured Vaporizing Chest Rub');
insert into todos (user_id, todo) values (924, 'AF Foam Sensitive Acne Pore Cleanser');
insert into todos (user_id, todo) values (490, 'bicalutamide');
insert into todos (user_id, todo) values (351, 'Sertraline Hydrochloride');
insert into todos (user_id, todo) values (410, 'Hydroxyzine Hydrochloride');
insert into todos (user_id, todo) values (637, 'Candida Albicans Remedy');
insert into todos (user_id, todo) values (390, 'Aveeno Active Naturals Hydrosport Sunblock');
insert into todos (user_id, todo) values (568, 'Oxybutynin Chloride');
insert into todos (user_id, todo) values (473, 'LBEL FILLING EFFECT FOUNDATION SPF 10');
insert into todos (user_id, todo) values (487, 'Helium');
insert into todos (user_id, todo) values (820, 'PROPOLIS');
insert into todos (user_id, todo) values (873, 'PIRMELLA 1/35');
insert into todos (user_id, todo) values (382, 'ZOVIRAX');
insert into todos (user_id, todo) values (838, 'Hydrocodone Bitartrate and Acetaminophen');
insert into todos (user_id, todo) values (254, 'Childrens Non-Drowsy');
insert into todos (user_id, todo) values (29, 'Leeks');
insert into todos (user_id, todo) values (105, 'Cold Sore Treatment');
insert into todos (user_id, todo) values (913, 'Minoxidil');
insert into todos (user_id, todo) values (44, 'Quetiapine Fumarate');
insert into todos (user_id, todo) values (354, 'Food - Plant Source, Almond Prunus amygdalus');
insert into todos (user_id, todo) values (562, 'Gas Relief');
insert into todos (user_id, todo) values (215, 'Hepatatox');
insert into todos (user_id, todo) values (60, 'ENALAPRIL MALEATE');
insert into todos (user_id, todo) values (229, 'Vistaril');
insert into todos (user_id, todo) values (138, 'Amino Mask');
insert into todos (user_id, todo) values (351, 'BEING WELL BODY');
insert into todos (user_id, todo) values (195, 'Spectracef');
insert into todos (user_id, todo) values (216, 'Sun Verbena Protective Body Protection SPF 15');
insert into todos (user_id, todo) values (82, 'Clean All');
insert into todos (user_id, todo) values (317, 'Humco Gentian Violet 1%');
insert into todos (user_id, todo) values (796, 'Methylphenidate Hydrochloride');
insert into todos (user_id, todo) values (692, 'SORBITOL');
insert into todos (user_id, todo) values (739, 'Doxepin Hydrochloride');
insert into todos (user_id, todo) values (69, 'acetaminophen');
insert into todos (user_id, todo) values (813, 'Lodosyn');
insert into todos (user_id, todo) values (916, 'ACER SACCHARUM POLLEN');
insert into todos (user_id, todo) values (605, 'Gabapentin');
insert into todos (user_id, todo) values (910, 'UREA');
insert into todos (user_id, todo) values (645, 'risperidone');
insert into todos (user_id, todo) values (291, 'Helium Oxygen Mixture');
insert into todos (user_id, todo) values (47, 'Anti Monkey Butt Diaper Rash');
insert into todos (user_id, todo) values (324, 'Full Care Alcohol Prep Pad');
insert into todos (user_id, todo) values (307, 'ISOPROPYL RUBBING ALCOHOL');
insert into todos (user_id, todo) values (489, 'minoxidil');
insert into todos (user_id, todo) values (325, 'Antibacterial Skin Cleanser 82');
insert into todos (user_id, todo) values (928, 'Peptic Relief');
insert into todos (user_id, todo) values (809, 'Ketek');
insert into todos (user_id, todo) values (242, 'Cabbage');
insert into todos (user_id, todo) values (146, 'Aspirin');
insert into todos (user_id, todo) values (718, 'Cyclosporine');
insert into todos (user_id, todo) values (77, 'Imiquimod');
insert into todos (user_id, todo) values (391, 'ALOEGUARD ANTIMICROBIAL');
insert into todos (user_id, todo) values (831, 'Miconazole Nitrate');
insert into todos (user_id, todo) values (378, 'Meprobamate');
insert into todos (user_id, todo) values (470, 'Diclofenac Sodium');
insert into todos (user_id, todo) values (569, 'Aspirin');
insert into todos (user_id, todo) values (296, 'Quetiapine fumarate');
insert into todos (user_id, todo) values (258, 'Moore Medical Extra Strength Non Aspirin');
insert into todos (user_id, todo) values (978, 'Be gone Sinus Congestion');
insert into todos (user_id, todo) values (297, 'Hydromorphone Hydrochloride');
insert into todos (user_id, todo) values (361, 'EQUUS CABALLUS SKIN');
insert into todos (user_id, todo) values (276, 'Calm Drops');
insert into todos (user_id, todo) values (352, 'Chlordiazepoxide Hydrochloride');
insert into todos (user_id, todo) values (599, 'formu care calcium antacid');
insert into todos (user_id, todo) values (131, 'Homeopathic Ringing Ear Formula');
insert into todos (user_id, todo) values (472, 'LIFT LUMIERE');
insert into todos (user_id, todo) values (262, 'RABBIT');
insert into todos (user_id, todo) values (362, 'Equate antacid');
insert into todos (user_id, todo) values (333, 'Lorcet 10/650');
insert into todos (user_id, todo) values (245, 'Treatment Set TS331977');
insert into todos (user_id, todo) values (111, 'Ifosfamide and Mesna');
insert into todos (user_id, todo) values (882, 'Benzoyl Peroxide');
insert into todos (user_id, todo) values (324, 'Lancome Paris High Resolution Refill 3X Triple Action Renewal Anti Wrinkle Broad Spectrum SPF 15 Sunscreen');
insert into todos (user_id, todo) values (159, 'Berkley and Jensen Omeprazole');
insert into todos (user_id, todo) values (576, 'BOBBI BROWN BRIGHTENING PROTECTIVE FACE BASE');
insert into todos (user_id, todo) values (418, 'Levofloxacin');
insert into todos (user_id, todo) values (955, 'Gilenya');
insert into todos (user_id, todo) values (340, 'Olanzapine');
insert into todos (user_id, todo) values (214, 'SPF 15 Sunscreen');
insert into todos (user_id, todo) values (330, 'Head and Shoulders');
insert into todos (user_id, todo) values (643, 'Aceon');
insert into todos (user_id, todo) values (340, 'Zolpidem Tartrate');
insert into todos (user_id, todo) values (833, 'Ketoconazole');
insert into todos (user_id, todo) values (623, 'Quetiapine Fumarate');
insert into todos (user_id, todo) values (345, 'wal dryl allergy');
insert into todos (user_id, todo) values (600, 'Temazepam');
insert into todos (user_id, todo) values (288, 'Aconitum Napellus Kit Refill');
insert into todos (user_id, todo) values (631, 'QUERCUS AGRIFOLIA POLLEN');
insert into todos (user_id, todo) values (793, 'MEDICLEAR DUAL SPOT DAY and NIGHT');
insert into todos (user_id, todo) values (603, 'Tact Cool');
insert into todos (user_id, todo) values (386, 'Antispetic');
insert into todos (user_id, todo) values (706, 'Stomach Relief');
insert into todos (user_id, todo) values (276, 'Solmeet Denti doctor');
insert into todos (user_id, todo) values (830, 'Methylphenidate Hydrochloride');
insert into todos (user_id, todo) values (906, 'Phytonadione');
insert into todos (user_id, todo) values (603, 'TERBINAFINE HYDROCHLORIDE');
insert into todos (user_id, todo) values (283, 'Lisinopril and Hydrochlorothiazide');
insert into todos (user_id, todo) values (286, 'HELLO FLAWLESS OXYGEN WOW Broad Spectrum SPF 25 BRIGHTENING MAKEUP - IM PLUSH AND PRECIOUS');
insert into todos (user_id, todo) values (591, 'Oxygen');
insert into todos (user_id, todo) values (209, 'ANTIBACTERIAL');
insert into todos (user_id, todo) values (331, 'PanOxyl');
insert into todos (user_id, todo) values (540, 'SHISEIDO UV PROTECTIVE FOUNDATION');
insert into todos (user_id, todo) values (675, 'ANTIBIOTIC PLUS PAIN RELIEF');
insert into todos (user_id, todo) values (476, 'Oxaprozin');
insert into todos (user_id, todo) values (479, 'Glipizide');
insert into todos (user_id, todo) values (956, 'Gabapentin');
insert into todos (user_id, todo) values (874, 'CLE DE PEAU BEAUTE REFINING FLUID FOUNDATION');
insert into todos (user_id, todo) values (603, 'Leader Sore throat');
insert into todos (user_id, todo) values (953, 'Gentle Laxative');
insert into todos (user_id, todo) values (311, 'Cefoxitin');
insert into todos (user_id, todo) values (367, 'Propranolol Hydrochloride');
insert into todos (user_id, todo) values (235, 'Quinidine Sulfate');
insert into todos (user_id, todo) values (939, 'Pollens - Weeds and Garden Plants, Plantain, English Plantago lanceolata');
insert into todos (user_id, todo) values (46, 'Hydrocodone Bitartrate and Acetaminophen');
insert into todos (user_id, todo) values (222, 'Oxygen');
insert into todos (user_id, todo) values (51, 'Scott-Vincent Borba');
insert into todos (user_id, todo) values (398, 'Tenzer');
insert into todos (user_id, todo) values (369, 'Meclizine Hydrochloride');
insert into todos (user_id, todo) values (279, 'Extra Strength Pain Reliever');
insert into todos (user_id, todo) values (618, 'Duloxetine');
insert into todos (user_id, todo) values (660, 'Metformin Hydrochloride');
insert into todos (user_id, todo) values (847, 'Preferred Plus 12 Hour Nasal');
insert into todos (user_id, todo) values (139, 'Old Spice Red Zone Collection After Hours');
insert into todos (user_id, todo) values (773, 'Topcare Cold Multi Symptom Severe');
insert into todos (user_id, todo) values (330, 'Intelence');
insert into todos (user_id, todo) values (505, 'Mineral Oil');
insert into todos (user_id, todo) values (486, 'Medium Cuts and Scratches');
insert into todos (user_id, todo) values (762, 'Jantoven');
insert into todos (user_id, todo) values (410, 'Intervene Makeup Broad Spectrum Sunscreen SPF 15 Soft Cognac');
insert into todos (user_id, todo) values (537, 'FENTANYL');
insert into todos (user_id, todo) values (488, 'Headache Relief');
insert into todos (user_id, todo) values (618, 'Clinical Strength MiracleDry Antiperspirant Deodorant AM');
insert into todos (user_id, todo) values (145, 'Vinotinto Hand Sanitizer');
insert into todos (user_id, todo) values (589, 'smart sense tussin dm');
insert into todos (user_id, todo) values (592, 'Methylin');
insert into todos (user_id, todo) values (839, 'RITE AID RENEWAL');
insert into todos (user_id, todo) values (526, 'Testosterone');
insert into todos (user_id, todo) values (721, 'SMART SENSE');
insert into todos (user_id, todo) values (380, 'Oxacillin');
insert into todos (user_id, todo) values (744, 'Flor-Opal Sustained-Release Fluoride');
insert into todos (user_id, todo) values (139, 'Metronidazole');
insert into todos (user_id, todo) values (346, 'Right Guard Total Defense Cool Peak');
insert into todos (user_id, todo) values (859, 'Ring Relief');
insert into todos (user_id, todo) values (84, 'Neutrogena Healthy Skin Compact Makeup');
insert into todos (user_id, todo) values (76, 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25');
insert into todos (user_id, todo) values (659, 'Lamotrigine');
insert into todos (user_id, todo) values (987, 'Spironolactone and Hydrochlorothiazide');
insert into todos (user_id, todo) values (906, 'Capmist DM');
insert into todos (user_id, todo) values (301, 'Hydralazine Hydrochloride');
insert into todos (user_id, todo) values (829, 'Levetiracetam');
insert into todos (user_id, todo) values (688, 'Miracle of Aloe Rub Roll On');
insert into todos (user_id, todo) values (790, 'Losartan Potassium');
insert into todos (user_id, todo) values (491, 'hemorrhoidal');
insert into todos (user_id, todo) values (746, 'ShopRite Ibuprophen');
insert into todos (user_id, todo) values (160, 'Marbeta 25 Kit');
insert into todos (user_id, todo) values (99, 'Clindamycin Palmitate Hydrochloride');
insert into todos (user_id, todo) values (814, 'Hydroxyzine Hydrochloride');
insert into todos (user_id, todo) values (836, 'FAMILY CARE ANTIBIOTIC');
insert into todos (user_id, todo) values (117, 'POLYETHYLENE GLYCOL 3350 AND ELECTROLYTES');
insert into todos (user_id, todo) values (659, 'Phoenix Balm');
insert into todos (user_id, todo) values (791, 'stool softener');
insert into todos (user_id, todo) values (531, 'Ibuprofen');
insert into todos (user_id, todo) values (636, 'Mar-cof BP');
insert into todos (user_id, todo) values (657, 'Treatment Set TS350393');
insert into todos (user_id, todo) values (882, 'Canary Grass Pollen');
insert into todos (user_id, todo) values (87, 'Lidodextrapine');
insert into todos (user_id, todo) values (169, 'ADVATE');
insert into todos (user_id, todo) values (891, 'Heparin Sodium');
insert into todos (user_id, todo) values (357, 'Dry Idea Advanced Dry');
insert into todos (user_id, todo) values (904, 'Dove Men plus Care');
insert into todos (user_id, todo) values (457, 'Insomnia');
insert into todos (user_id, todo) values (688, 'Viscum Crataegus');
insert into todos (user_id, todo) values (599, 'DIGOX');
insert into todos (user_id, todo) values (234, 'Dramamine Less Drowsy');
insert into todos (user_id, todo) values (542, 'PRAMIPEXOLE DIHYDROCHLORIDE');
insert into todos (user_id, todo) values (530, 'good neighbor pharmacy ibuprofen');
insert into todos (user_id, todo) values (749, 'CVS Aspirin');
insert into todos (user_id, todo) values (760, 'Acyclovir');
insert into todos (user_id, todo) values (761, 'THERA Moisturizing Body Cleanser');
insert into todos (user_id, todo) values (352, 'Glyburide (micronized) and Metformin Hydrochloride');
insert into todos (user_id, todo) values (936, 'Tramadol Hydrochloride');
insert into todos (user_id, todo) values (38, 'Trazodone Hydrochloride');
insert into todos (user_id, todo) values (621, 'Disopyramide Phosphate');
insert into todos (user_id, todo) values (533, 'Colgate Optic White Sparkling Mint Flavor');
insert into todos (user_id, todo) values (608, 'Cephalexin');
insert into todos (user_id, todo) values (171, 'Health Mart Sleep Aid');
insert into todos (user_id, todo) values (101, 'Alternaria alternata');
insert into todos (user_id, todo) values (525, 'Reed Canary Grass');
insert into todos (user_id, todo) values (82, 'RUMEX CRISPUS POLLEN');
insert into todos (user_id, todo) values (838, 'Estradiol');
insert into todos (user_id, todo) values (187, 'Miconazole 7');
insert into todos (user_id, todo) values (773, 'Lithium Carbonate');
insert into todos (user_id, todo) values (424, 'PRAVASTATIN SODIUM');
insert into todos (user_id, todo) values (780, 'Bullfrog Surfer');
insert into todos (user_id, todo) values (335, 'ESTRADIOL VALERATE');
insert into todos (user_id, todo) values (778, 'Morphine Sulfate');
insert into todos (user_id, todo) values (748, 'Lipitor');
insert into todos (user_id, todo) values (416, 'Kroger');
insert into todos (user_id, todo) values (329, 'Pediatric Infuvite Multiple Vitamins for Infusion');
insert into todos (user_id, todo) values (176, 'PINUS STROBUS POLLEN');
insert into todos (user_id, todo) values (833, 'HAMSTER HAIR AND EPITHELIA');
insert into todos (user_id, todo) values (692, 'Medicated Dandruff');
insert into todos (user_id, todo) values (409, 'Colgate');
insert into todos (user_id, todo) values (825, 'ERTACZO');
insert into todos (user_id, todo) values (49, 'NATALVIRT CA');
insert into todos (user_id, todo) values (19, 'Little Colds Sore Throat Relief Melt Aways');
insert into todos (user_id, todo) values (508, 'Lunesta');
insert into todos (user_id, todo) values (257, 'LOreal Paris Advanced Suncare Silky Sheer Face 50 Plus Broad Spectrum SPF 50 Plus Sunscreen');
insert into todos (user_id, todo) values (235, 'Constipation');
insert into todos (user_id, todo) values (915, 'Sensodyne Complete Protection');
insert into todos (user_id, todo) values (738, 'Neutrogena Tgel Daily Control 2 in 1');
insert into todos (user_id, todo) values (991, 'Tummy Upset');
insert into todos (user_id, todo) values (263, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (884, 'Family Wellness Acid Reducer');
insert into todos (user_id, todo) values (782, 'OMNIPAQUE');
insert into todos (user_id, todo) values (198, 'Doral');
insert into todos (user_id, todo) values (78, 'Escitalopram Oxalate');
insert into todos (user_id, todo) values (494, 'Estrogen');
insert into todos (user_id, todo) values (407, 'OXYGEN');
insert into todos (user_id, todo) values (821, 'fexofenadine hydrochloride');
insert into todos (user_id, todo) values (111, 'Dicyclomine Hydrochloride');
insert into todos (user_id, todo) values (10, 'Oxygen');
insert into todos (user_id, todo) values (530, 'Maprotiline Hydrochloride');
insert into todos (user_id, todo) values (454, 'Fluconazole');
insert into todos (user_id, todo) values (571, 'Propranolol Hydrochloride');
insert into todos (user_id, todo) values (988, 'Home Health Everclean Antidandruff');
insert into todos (user_id, todo) values (899, 'Standardized Grass Pollen, Timothy');
insert into todos (user_id, todo) values (770, 'Cefuroxime axetil');
insert into todos (user_id, todo) values (671, 'DigiKlenz Antibacterial Hand Soap');
insert into todos (user_id, todo) values (440, 'Hielo Ardiente');
insert into todos (user_id, todo) values (604, 'Clarithromycin');
insert into todos (user_id, todo) values (102, 'Clearskin');
insert into todos (user_id, todo) values (529, 'TRIHEXYPHENIDYL HYDROCHLORIDE');
insert into todos (user_id, todo) values (65, 'ZALEPLON');
insert into todos (user_id, todo) values (505, 'Tag Alder');
insert into todos (user_id, todo) values (589, 'Azathioprine');
insert into todos (user_id, todo) values (352, 'harmon face values minoxidil');
insert into todos (user_id, todo) values (355, 'BestHealth Cough Suppressant SUGAR FREE HONEY LEMON FLAVOR');
insert into todos (user_id, todo) values (692, 'Ropinirole');
insert into todos (user_id, todo) values (581, 'Vamousse Lice Prevention');
insert into todos (user_id, todo) values (82, 'Tobramycin and Dexamethasone');
insert into todos (user_id, todo) values (442, 'Seaweed Aqua Massage');
insert into todos (user_id, todo) values (403, 'Collagen 6 Special Order');
insert into todos (user_id, todo) values (40, 'Zyclara');
insert into todos (user_id, todo) values (650, 'Mischievous Orange Antibacterial Foaming Hand Wash');
insert into todos (user_id, todo) values (262, 'LAMICTAL');
insert into todos (user_id, todo) values (996, 'Diazepam');
insert into todos (user_id, todo) values (294, '3 Hand Sanitizers');
insert into todos (user_id, todo) values (555, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (124, 'Halls');
insert into todos (user_id, todo) values (853, 'INDOMETHACIN');
insert into todos (user_id, todo) values (380, 'FENTANYL CITRATE');
insert into todos (user_id, todo) values (113, 'Plantago Primula');
insert into todos (user_id, todo) values (932, 'Aspirin');
insert into todos (user_id, todo) values (27, 'Extra Strength Medicated Body');
insert into todos (user_id, todo) values (828, 'Neutrogena Ultra Sheer Dry Touch Sunblock');
insert into todos (user_id, todo) values (732, 'Icy Hot Power Gel');
insert into todos (user_id, todo) values (159, 'ASPERGILLUS FUMIGATUS');
insert into todos (user_id, todo) values (865, 'Arnica Retina');
insert into todos (user_id, todo) values (841, 'Medrox');
insert into todos (user_id, todo) values (635, 'Prevention daily tinted mositurizer oil-free Tinted 30');
insert into todos (user_id, todo) values (703, 'Loxapine');
insert into todos (user_id, todo) values (162, 'Anti-Diarrheal');
insert into todos (user_id, todo) values (530, 'HYDROCORTISONE');
insert into todos (user_id, todo) values (619, 'Amikacin Sulfate');
insert into todos (user_id, todo) values (287, 'Reglan');
insert into todos (user_id, todo) values (781, 'Fludarabine');
insert into todos (user_id, todo) values (652, 'Pollens - Trees, Mulberry Mix');
insert into todos (user_id, todo) values (978, 'LOVASTATIN');
insert into todos (user_id, todo) values (394, 'Gabapentin');
insert into todos (user_id, todo) values (673, 'Treatment Set TS350257');
insert into todos (user_id, todo) values (507, 'Atropine Sulfate');
insert into todos (user_id, todo) values (621, 'NARS FOUNDATION');
insert into todos (user_id, todo) values (761, 'Icy Hot No Mess Vapor Cough Suppresant');
insert into todos (user_id, todo) values (98, 'meijer');
insert into todos (user_id, todo) values (864, 'Aspirin');
insert into todos (user_id, todo) values (1000, 'Antimonium Tart Kit Refill');
insert into todos (user_id, todo) values (866, 'Haloperidol Decanoate');
insert into todos (user_id, todo) values (503, 'Olanzapine');
insert into todos (user_id, todo) values (305, 'Spongia Aurum');
insert into todos (user_id, todo) values (97, 'elave Age Delay Daily Lip Defence');
insert into todos (user_id, todo) values (518, 'UltrasolSunscreen');
insert into todos (user_id, todo) values (575, 'ShopRite Cough DM');
insert into todos (user_id, todo) values (801, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (127, 'Americaine');
insert into todos (user_id, todo) values (256, 'Ceftriaxone');
insert into todos (user_id, todo) values (374, 'CUCUMBER');
insert into todos (user_id, todo) values (747, 'TUMS');
insert into todos (user_id, todo) values (832, 'equaline');
insert into todos (user_id, todo) values (295, 'Dreumex Omnicare');
insert into todos (user_id, todo) values (992, 'Anti-Bacterial Hand');
insert into todos (user_id, todo) values (855, 'Moist SURE');
insert into todos (user_id, todo) values (446, 'Bluefish');
insert into todos (user_id, todo) values (270, 'Eyewash Station Additive Concentrate');
insert into todos (user_id, todo) values (945, 'Health Care Instant Hand Sanitizer Ice Clear');
insert into todos (user_id, todo) values (460, 'Clobex');
insert into todos (user_id, todo) values (752, 'Olanzapine');
insert into todos (user_id, todo) values (165, 'Etodolac');
insert into todos (user_id, todo) values (704, 'Dark Spot Corrector');
insert into todos (user_id, todo) values (342, '24 HOUR');
insert into todos (user_id, todo) values (869, 'Cinnabar Dandelion Cold Relief');
insert into todos (user_id, todo) values (407, 'Nifedipine');
insert into todos (user_id, todo) values (503, 'Oxygen');
insert into todos (user_id, todo) values (111, 'Tartar control plus');
insert into todos (user_id, todo) values (558, 'Altipres');
insert into todos (user_id, todo) values (405, 'OxyContin');
insert into todos (user_id, todo) values (226, 'FRAXINUS VELUTINA POLLEN');
insert into todos (user_id, todo) values (58, 'Phentermine hydrochloride');
insert into todos (user_id, todo) values (162, 'antacid');
insert into todos (user_id, todo) values (300, 'Losartan potassium Tablets, 100 mg');
insert into todos (user_id, todo) values (168, 'simply right night time');
insert into todos (user_id, todo) values (452, 'Triple Flu Defense');
insert into todos (user_id, todo) values (808, 'Torsemide');
insert into todos (user_id, todo) values (599, 'Perphenazine');
insert into todos (user_id, todo) values (373, 'Levemir');
insert into todos (user_id, todo) values (146, 'Levitra');
insert into todos (user_id, todo) values (29, 'NightTime');
insert into todos (user_id, todo) values (852, 'Quetiapine fumarate');
insert into todos (user_id, todo) values (679, 'RIVASTIGMINE TARTRATE');
insert into todos (user_id, todo) values (643, 'Cromolyn Sodium');
insert into todos (user_id, todo) values (665, 'False Ragweed');
insert into todos (user_id, todo) values (384, 'leader Antacid');
insert into todos (user_id, todo) values (985, 'Eucerin Daily Protection Body');
insert into todos (user_id, todo) values (305, 'Warfarin Sodium');
insert into todos (user_id, todo) values (412, 'Simvastatin');
insert into todos (user_id, todo) values (674, 'modafinil');
insert into todos (user_id, todo) values (420, 'Dust, House Mixture');
insert into todos (user_id, todo) values (381, 'AllergyEase Dust Mites and Roaches');
insert into todos (user_id, todo) values (362, 'Albuterol Sulfate');
insert into todos (user_id, todo) values (374, 'good sense cold head congestion');
insert into todos (user_id, todo) values (26, 'Head and Shoulders Conditioner');
insert into todos (user_id, todo) values (612, 'Tobacco Leaf');
insert into todos (user_id, todo) values (751, 'Leg Cramp Relief');
insert into todos (user_id, todo) values (205, 'Ranitidine');
insert into todos (user_id, todo) values (928, 'allergy and congestion relief');
insert into todos (user_id, todo) values (606, 'Extended Phenytoin Sodium');
insert into todos (user_id, todo) values (950, 'Ladys Choice Invisible Solid');
insert into todos (user_id, todo) values (937, 'Smart Sense All Day Allergy D');
insert into todos (user_id, todo) values (114, 'Natrum Muriaticum');
insert into todos (user_id, todo) values (238, 'Fluconazole');
insert into todos (user_id, todo) values (331, 'OXYGEN');
insert into todos (user_id, todo) values (167, 'LMD in Dextrose');
insert into todos (user_id, todo) values (241, 'Cocculus Indicus Kit Refill');
insert into todos (user_id, todo) values (515, 'Instant Hand Sanitizer Gel');
insert into todos (user_id, todo) values (677, 'Loratadine and Pseudoephedrine Sulfate');
insert into todos (user_id, todo) values (462, 'Oxacillin');
insert into todos (user_id, todo) values (48, 'care one ibuprofen');
insert into todos (user_id, todo) values (237, 'vanarex hair regrowth treatment');
insert into todos (user_id, todo) values (450, 'CELEBREX');
insert into todos (user_id, todo) values (93, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (239, 'equaline all day pain relief');
insert into todos (user_id, todo) values (873, 'STOOL SOFTENER DOCUSATE SODIUM 50 MG');
insert into todos (user_id, todo) values (863, 'Furosemide');
insert into todos (user_id, todo) values (588, 'PLANTAGO LANCEOLATA POLLEN');
insert into todos (user_id, todo) values (718, 'KENALOG-40');
insert into todos (user_id, todo) values (532, 'Sugar Maple');
insert into todos (user_id, todo) values (659, 'Diltiazem Hydrochloride');
insert into todos (user_id, todo) values (209, 'ESSENTIAL SOLUTION VITA A MASK SHEET');
insert into todos (user_id, todo) values (307, 'Cerebellum Thalamus A Aurum');
insert into todos (user_id, todo) values (741, 'Metoprolol succinate');
insert into todos (user_id, todo) values (441, 'CYPROHEPTADINE HYDROCHLORIDE');
insert into todos (user_id, todo) values (984, 'White Mulbery Pollen');
insert into todos (user_id, todo) values (551, 'Medicine Shoppe Allergy Relief D24');
insert into todos (user_id, todo) values (449, 'Fluconazole');
insert into todos (user_id, todo) values (444, 'WHITE FLOWER ANALGESIC BALM');
insert into todos (user_id, todo) values (224, 'Dye-Free Wal-Dryl');
insert into todos (user_id, todo) values (311, 'Acne');
insert into todos (user_id, todo) values (689, 'donepezil hydrochloride');
insert into todos (user_id, todo) values (441, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (545, 'HAMSOA ATOBY MEDI');
insert into todos (user_id, todo) values (473, 'Tivorbex');
insert into todos (user_id, todo) values (920, 'CLARINS Broad Spectrum SPF 15 Sunscreen Extra-Firming Foundation Tint 108');
insert into todos (user_id, todo) values (626, 'Ampicillin and Sulbactam');
insert into todos (user_id, todo) values (424, 'Zolpidem Tartrate');
insert into todos (user_id, todo) values (879, 'FRAXINUS AMERICANA POLLEN');
insert into todos (user_id, todo) values (776, 'Glipizide and Metformin Hydrochloride');
insert into todos (user_id, todo) values (480, 'venlafaxine');
insert into todos (user_id, todo) values (273, 'Cough HP');
insert into todos (user_id, todo) values (884, 'Sugar Free Cherry Fishermans Friend Menthol Cough Suppressant');
insert into todos (user_id, todo) values (549, 'Lamotrigine');
insert into todos (user_id, todo) values (510, 'Childrens Loratadine');
insert into todos (user_id, todo) values (857, 'ACT Anticavity Kids iCarly Fluoride');
insert into todos (user_id, todo) values (97, 'tizanidine hydrochloride');
insert into todos (user_id, todo) values (263, 'Oxycodone and Acetaminophen');
insert into todos (user_id, todo) values (398, 'Amlodipine besylate and Atorvastatin calcium');
insert into todos (user_id, todo) values (184, 'Black Oak');
insert into todos (user_id, todo) values (991, 'Obstetrical Antiseptic');
insert into todos (user_id, todo) values (769, 'Glyburide');
insert into todos (user_id, todo) values (759, 'Ring Relief');
insert into todos (user_id, todo) values (393, 'COLDS COUGHS');
insert into todos (user_id, todo) values (33, 'Duet DHA');
insert into todos (user_id, todo) values (225, 'Levetiracetam');
insert into todos (user_id, todo) values (644, 'CVS Pharmacy Sport SPF 50');
insert into todos (user_id, todo) values (834, 'Rugby Nicotine Polacrilex Gum, Coated Mint Flavor');
insert into todos (user_id, todo) values (768, 'GEODON');
insert into todos (user_id, todo) values (706, 'Regular Strength Sleep-Aid');
insert into todos (user_id, todo) values (467, 'Colestipol Hydrochloride');
insert into todos (user_id, todo) values (23, 'Loratadine');
insert into todos (user_id, todo) values (113, 'Potassium Chloride in Dextrose');
insert into todos (user_id, todo) values (914, 'Givenchy TEINT COUTURE Long Wearing Fluid Foundation with Sunscreen Broad Spectrum SPF 20 ELEGANT BROWN');
insert into todos (user_id, todo) values (703, 'Bethanechol Chloride');
insert into todos (user_id, todo) values (658, '4 in 1 Pressed Mineral SPF 15 Deep');
insert into todos (user_id, todo) values (79, 'Trandolapril and Verapamil Hydrochloride');
insert into todos (user_id, todo) values (460, 'COUGH HICCOUGH');
insert into todos (user_id, todo) values (942, 'Cephalexin');
insert into todos (user_id, todo) values (881, 'Hydrochlorothiazide');
insert into todos (user_id, todo) values (365, 'BACTROBAN');
insert into todos (user_id, todo) values (231, 'Equate Miconazole 1');
insert into todos (user_id, todo) values (858, 'Kaiser Permanente');
insert into todos (user_id, todo) values (362, 'Perfecting Liquid Foundation Earthy Beige');
insert into todos (user_id, todo) values (998, 'Nux vomica');
insert into todos (user_id, todo) values (781, 'TUMS');
insert into todos (user_id, todo) values (624, 'PUTTO ATO SECRET UV FACE');
insert into todos (user_id, todo) values (939, 'LOreal Paris Advanced Suncare Silky Sheer Face 30 Broad Spectrum SPF 30 Sunscreen');
insert into todos (user_id, todo) values (848, 'Visible Difference Gentle Hydrating Broad Spectrum Sunscreen SPF 15');
insert into todos (user_id, todo) values (468, 'Levocetirizine Dihydrochloride');
insert into todos (user_id, todo) values (608, 'Gabapentin');
insert into todos (user_id, todo) values (272, 'Ciprofloxacin');
insert into todos (user_id, todo) values (352, 'Stress Control / Controle Du Stress');
insert into todos (user_id, todo) values (908, 'Manefit Beauty Planner Lily Whitening Eye Patch');
insert into todos (user_id, todo) values (301, 'Ultram');
insert into todos (user_id, todo) values (249, 'SudoGest');
insert into todos (user_id, todo) values (333, 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25');
insert into todos (user_id, todo) values (199, 'NO-AD 45 Sunscreen');
insert into todos (user_id, todo) values (717, 'HELMINTHOSPORIUM SOLANI');
insert into todos (user_id, todo) values (504, 'Vivelle-Dot');
insert into todos (user_id, todo) values (276, 'Fentanyl');
insert into todos (user_id, todo) values (529, 'Pseudoephedrine Hydrochloride');
insert into todos (user_id, todo) values (176, 'Vacuant');
insert into todos (user_id, todo) values (771, 'Glipizide');
insert into todos (user_id, todo) values (794, 'THERASEPTIN');
insert into todos (user_id, todo) values (941, 'Hydromorphone Hydrochloride');
insert into todos (user_id, todo) values (432, 'No7 Beautifully Matte Foundation Sunscreen Broad Spectrum SPF 15 Mocha');
insert into todos (user_id, todo) values (472, 'Ibuprofen');
insert into todos (user_id, todo) values (811, 'CPD/ADSOL');
insert into todos (user_id, todo) values (375, 'LEADER ANTI ITCH MAXIMUM STRENGTH');
insert into todos (user_id, todo) values (813, 'Sulindac');
insert into todos (user_id, todo) values (589, 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)');
insert into todos (user_id, todo) values (559, 'Wal Fex Allergy');
insert into todos (user_id, todo) values (254, 'Gelato Topical Anesthetic');
insert into todos (user_id, todo) values (255, 'Natureplex Hydrocortisone');
insert into todos (user_id, todo) values (900, 'DryMax');
insert into todos (user_id, todo) values (159, 'piperacillin and tazobactam');
insert into todos (user_id, todo) values (81, 'NITROGEN');
insert into todos (user_id, todo) values (581, 'Tinidazole');
insert into todos (user_id, todo) values (279, 'Ofloxacin');
insert into todos (user_id, todo) values (955, 'Retin-A');
insert into todos (user_id, todo) values (807, 'Bystolic');
insert into todos (user_id, todo) values (948, 'Rivastigmine Tartrate');
insert into todos (user_id, todo) values (384, 'Food Service Soap');
insert into todos (user_id, todo) values (382, 'PURELL Advanced Hand Sanitizer Ocean Kiss');
insert into todos (user_id, todo) values (421, 'topiramate');
insert into todos (user_id, todo) values (558, 'Azithromycin Dihydrate');
insert into todos (user_id, todo) values (447, 'Grippe HP');
insert into todos (user_id, todo) values (931, 'Diflucan');
insert into todos (user_id, todo) values (87, 'SMART SENSE');
insert into todos (user_id, todo) values (70, 'Fludeoxyglucose F-18');
insert into todos (user_id, todo) values (469, 'Oxistat');
insert into todos (user_id, todo) values (4, 'Digoxin');
insert into todos (user_id, todo) values (362, 'Purminerals 4-in-1 Mineral Tinted Moisturizer Broad Spectrum SPF 20 (DARK)');
insert into todos (user_id, todo) values (426, 'Aveeno Anti Itch Concentrated');
insert into todos (user_id, todo) values (164, 'Stomach Relief Anti Diarrheal');
insert into todos (user_id, todo) values (126, 'Equaline muscle rub');
insert into todos (user_id, todo) values (957, 'Simvastatin');
insert into todos (user_id, todo) values (37, 'Naloxone Hydrochloride');
insert into todos (user_id, todo) values (400, 'PURIXAN');
insert into todos (user_id, todo) values (16, 'Leucovorin Calcium');
insert into todos (user_id, todo) values (271, 'Loratadine and Pseudoephedrine');
insert into todos (user_id, todo) values (391, 'AVINZA');
insert into todos (user_id, todo) values (756, 'Bethanechol Chloride');
insert into todos (user_id, todo) values (148, 'Jason Healthy Mouth Anticavity ,Tartar Control Tea Tree Oil and Cinnamon');
insert into todos (user_id, todo) values (512, 'Sleep Assist');
insert into todos (user_id, todo) values (447, 'MIRTAZAPINE');
insert into todos (user_id, todo) values (78, 'Pier 1 Imports Crisp Bamboo Anti-Bacterial Hand Sanitizer');
insert into todos (user_id, todo) values (112, 'COUMADIN');
insert into todos (user_id, todo) values (173, 'ENTOCORT');
insert into todos (user_id, todo) values (370, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (596, 'Covergirl Queen Collection All Day Flawless 3in1 Foundation');
insert into todos (user_id, todo) values (2, 'Quality Choice Extra Strength Pain Relief');
insert into todos (user_id, todo) values (178, 'Mycophenolate Mofetil');
insert into todos (user_id, todo) values (33, 'Hawaiian Tropic Kids SPF 30');
insert into todos (user_id, todo) values (559, 'Nabumetone');
insert into todos (user_id, todo) values (84, 'Aspergillus terreus');
insert into todos (user_id, todo) values (841, 'pain relief');
insert into todos (user_id, todo) values (736, 'COREG');
insert into todos (user_id, todo) values (933, 'SNAPPY APPLE SCENTED HAND SANITIZER');
insert into todos (user_id, todo) values (29, 'Octreotide Acetate');
insert into todos (user_id, todo) values (671, 'SHISEIDO RADIANT LIFTING FOUNDATION');
insert into todos (user_id, todo) values (38, 'Doxercalciferol');
insert into todos (user_id, todo) values (209, 'CVS Daily Acne Clearing Scrub');
insert into todos (user_id, todo) values (875, 'Medique Medi-Phenyl');
insert into todos (user_id, todo) values (944, 'Pollens - Trees, Olive Olea europaea');
insert into todos (user_id, todo) values (630, 'Olanzapine');
insert into todos (user_id, todo) values (452, 'TIZANIDINE HYDROCHLORIDE');
insert into todos (user_id, todo) values (820, 'Natural Fiber Powder');
insert into todos (user_id, todo) values (490, 'Lidocaine');
insert into todos (user_id, todo) values (310, 'RHODOTORULA RUBRA');
insert into todos (user_id, todo) values (494, 'Nifedipine');
insert into todos (user_id, todo) values (775, 'V-Natal');
insert into todos (user_id, todo) values (359, 'Meperidine Hydrochloride');
insert into todos (user_id, todo) values (320, 'TOPIRAMATE');
insert into todos (user_id, todo) values (862, 'PREDNISOLONE SODIUM PHOSPHATE');
insert into todos (user_id, todo) values (407, 'Calcarea Carbonica Kit Refill');
insert into todos (user_id, todo) values (521, 'benazepril hydrochloride and hydrochlorothiazide');
insert into todos (user_id, todo) values (804, 'Verapamil Hydrochloride');
insert into todos (user_id, todo) values (42, 'Cold and Infection Defense');
insert into todos (user_id, todo) values (930, 'pharMAX fibro');
insert into todos (user_id, todo) values (733, 'Sweet Peaches Antibacterial Foaming Hand Wash');
insert into todos (user_id, todo) values (194, 'Duloxetine Hydrochloride');
insert into todos (user_id, todo) values (933, 'Preferred Plus Hemorrhoid');
insert into todos (user_id, todo) values (482, 'BALD CYPRESS POLLEN');
insert into todos (user_id, todo) values (959, 'Colloidal Silver');
insert into todos (user_id, todo) values (877, 'Ofloxacin');
insert into todos (user_id, todo) values (994, 'Levofloxacin');
insert into todos (user_id, todo) values (321, 'Rolaids Ultra Strength Mint');
insert into todos (user_id, todo) values (400, 'Pier 1 Imports Blueberry Parfait Anti-Bacterial Hand Sanitizer');
insert into todos (user_id, todo) values (293, 'Sleep Aid');
insert into todos (user_id, todo) values (558, 'Hydrochlorothiazide');
insert into todos (user_id, todo) values (667, 'Omeprazole');
insert into todos (user_id, todo) values (180, 'Pier 1 Imports Ocean Water Anti-bacterial Hand Wash');
insert into todos (user_id, todo) values (827, 'DualSenses Scalp Regulation Anti-Dandruff Shampoo');
insert into todos (user_id, todo) values (298, 'Tranexamic Acid');
insert into todos (user_id, todo) values (453, 'Ibuprofen');
insert into todos (user_id, todo) values (874, 'Urea');
insert into todos (user_id, todo) values (547, '2 in 1');
insert into todos (user_id, todo) values (247, 'Sore Throat Relief');
insert into todos (user_id, todo) values (882, 'Pleo Not');
insert into todos (user_id, todo) values (487, 'Isoniazid');
insert into todos (user_id, todo) values (355, 'FAMOTIDINE');
insert into todos (user_id, todo) values (124, 'BOA VIDA Recovery Creme');
insert into todos (user_id, todo) values (723, 'Entacapone');
insert into todos (user_id, todo) values (645, 'phentermine hydrochloride');
insert into todos (user_id, todo) values (732, 'Cosyntropin');
insert into todos (user_id, todo) values (892, 'Arnica Plus');
insert into todos (user_id, todo) values (470, 'Triamterene and Hydrochlorothiazide');
insert into todos (user_id, todo) values (702, 'EQUALINE');
insert into todos (user_id, todo) values (659, 'OXYGEN');
insert into todos (user_id, todo) values (106, 'FENTANYL TRANSDERMAL SYSTEM');
insert into todos (user_id, todo) values (853, 'MUCUS RELIEF');
insert into todos (user_id, todo) values (168, 'nasal');
insert into todos (user_id, todo) values (240, 'Health Mart Calcium antacid Assorted Fruit');
insert into todos (user_id, todo) values (76, 'FEXOFENADINE HYDROCHLORIDE and PSEUDOEPHEDRINE HYDROCHLORIDE');
insert into todos (user_id, todo) values (629, 'Aurum Equisetum B');
insert into todos (user_id, todo) values (584, 'Bupropion Hydrochloride');
insert into todos (user_id, todo) values (54, 'Citalopram');
insert into todos (user_id, todo) values (255, 'Clorazepate Dipotassium');
insert into todos (user_id, todo) values (382, 'Hemorrhoidal');
insert into todos (user_id, todo) values (30, 'Butalbital, Aspirin and Caffeine');
insert into todos (user_id, todo) values (790, 'Morphine Sulfate');
insert into todos (user_id, todo) values (729, 'Fludeoxyglucose');
insert into todos (user_id, todo) values (74, 'Incruse Ellipta');
insert into todos (user_id, todo) values (26, 'Mirtazapine');
insert into todos (user_id, todo) values (663, 'ARANESP');
insert into todos (user_id, todo) values (859, 'Duane Reade');
insert into todos (user_id, todo) values (623, 'Professional Therapy');
insert into todos (user_id, todo) values (700, 'Holiday Treats Antibacterial Foaming Hand Wash');
insert into todos (user_id, todo) values (383, 'CYZONE');
insert into todos (user_id, todo) values (622, 'Zyclara');
insert into todos (user_id, todo) values (503, 'Carbidopa, levodopa and entacapone');
insert into todos (user_id, todo) values (860, 'Sore Throat');
insert into todos (user_id, todo) values (93, 'Aureobasidium pullulans');
insert into todos (user_id, todo) values (611, 'Neurontin');
insert into todos (user_id, todo) values (160, 'Thyro Aid');
insert into todos (user_id, todo) values (469, 'Advanced relief');
insert into todos (user_id, todo) values (200, 'All Day Allergy-D');
insert into todos (user_id, todo) values (797, 'Dimenhydrinate');
insert into todos (user_id, todo) values (38, 'Purpose');
insert into todos (user_id, todo) values (354, 'Liothyronine Sodium');
insert into todos (user_id, todo) values (548, 'Tussin DM');
insert into todos (user_id, todo) values (680, 'MRCL');
insert into todos (user_id, todo) values (239, 'Cefuroxime axetil');
insert into todos (user_id, todo) values (647, 'flormar Foundation Sunscreen Broad Spectrum SPF 20 LF13 GOLDEN BEIGE');
insert into todos (user_id, todo) values (942, 'OXYGEN');
insert into todos (user_id, todo) values (598, 'Candida High Potency 9');
insert into todos (user_id, todo) values (29, 'Omeprazole');
insert into todos (user_id, todo) values (399, 'HELMINTHOSPORIUM SOLANI');
insert into todos (user_id, todo) values (148, 'Body Luxuries English Pear Scented Waterless Anti Bacterial Hand gel');
insert into todos (user_id, todo) values (361, 'Atorvastatin Calcium');
insert into todos (user_id, todo) values (111, 'Dermasil Sensitive');
insert into todos (user_id, todo) values (203, 'VALACYCLOVIR HYDROCHLORIDE');
insert into todos (user_id, todo) values (784, 'Psoriasin');
insert into todos (user_id, todo) values (786, 'Amitiza');
insert into todos (user_id, todo) values (468, 'Degree');
insert into todos (user_id, todo) values (467, 'WSNA Hand Sanitizer');
insert into todos (user_id, todo) values (964, 'Purminerals 4 in 1 Makeup SPF 15 Dark');
insert into todos (user_id, todo) values (104, 'Oral Assist');
insert into todos (user_id, todo) values (972, 'TERBUTALINE SULFATE');
insert into todos (user_id, todo) values (176, 'Leader Allergy D 12');
insert into todos (user_id, todo) values (873, 'Aspirin');
insert into todos (user_id, todo) values (223, 'SunZone Sunscreen Family SPF 30');
insert into todos (user_id, todo) values (540, 'XtraCare Hand Sanitizer');
insert into todos (user_id, todo) values (537, 'Leader Aller Ease');
insert into todos (user_id, todo) values (700, 'Imiquimod');
insert into todos (user_id, todo) values (804, 'ATORVASTATIN CALCIUM');
insert into todos (user_id, todo) values (946, 'Clotrimazole');
insert into todos (user_id, todo) values (480, 'Sodium Sulfacetamide, Sulfur');
insert into todos (user_id, todo) values (246, 'Topical');
insert into todos (user_id, todo) values (402, 'Sunmark');
insert into todos (user_id, todo) values (650, 'BENZPHETAMINE HYDROCHLORIDE');
insert into todos (user_id, todo) values (269, 'Ranitidine Hydrochloride');
insert into todos (user_id, todo) values (23, 'BeneFIX');
insert into todos (user_id, todo) values (356, 'CVS Hemorrhoidal Topical Analgesic');
insert into todos (user_id, todo) values (90, 'Opana');
insert into todos (user_id, todo) values (277, 'Budesonide');
insert into todos (user_id, todo) values (893, 'ESIKA');
insert into todos (user_id, todo) values (749, 'MBM 12 Male');
insert into todos (user_id, todo) values (994, 'childrens fever reducer and pain reliever');
insert into todos (user_id, todo) values (233, 'Ragweed Mixture');
insert into todos (user_id, todo) values (651, 'Dandruff Daily Care');
insert into todos (user_id, todo) values (334, 'anti diarrheal');
insert into todos (user_id, todo) values (356, 'Botrytis cinerea');
insert into todos (user_id, todo) values (364, 'Neomycin and Polymyxin B Sulfates and Hydrocortisone');
insert into todos (user_id, todo) values (131, 'AVANDARYL');
insert into todos (user_id, todo) values (506, 'DAMOAE THERAPY');
insert into todos (user_id, todo) values (200, 'Trifluridine');
insert into todos (user_id, todo) values (25, 'Antiseptic Mouth Rinse');
insert into todos (user_id, todo) values (80, 'Shopko');
insert into todos (user_id, todo) values (288, 'Benzoyl Peroxide');
insert into todos (user_id, todo) values (574, 'Pollens - Trees, Elm, American Ulmus americana');
insert into todos (user_id, todo) values (308, 'Sorrel Mixture');
insert into todos (user_id, todo) values (503, 'Anticoagulant Citrate Dextrose A');
insert into todos (user_id, todo) values (288, 'Omeprazole');
insert into todos (user_id, todo) values (748, 'Lidocaine');
insert into todos (user_id, todo) values (309, 'Glimepiride');
insert into todos (user_id, todo) values (552, 'Ginseng Khan');
insert into todos (user_id, todo) values (901, 'Triamterene and Hydrochlorothiazide');
insert into todos (user_id, todo) values (809, 'Nitrofurantoin Macrocrystals');
insert into todos (user_id, todo) values (173, 'Valsartan and Hydrochlorothiazide');
insert into todos (user_id, todo) values (151, 'Lyrica');
insert into todos (user_id, todo) values (703, 'Erythromycin');
insert into todos (user_id, todo) values (147, 'CLARINS BROAD SPECTRUM SPF 15 - Sunscreen Multi-Active Day Early wrinkle correcting');
insert into todos (user_id, todo) values (654, 'Athomer baby');
insert into todos (user_id, todo) values (693, 'SHISEIDO THE MAKEUP FOUNDATION');
insert into todos (user_id, todo) values (708, 'BencoCaine Topical Anesthetic');
insert into todos (user_id, todo) values (739, 'Clobetasol Propionate');
insert into todos (user_id, todo) values (242, 'Cefuroxime');
insert into todos (user_id, todo) values (619, 'NATURAL HONEY HERB COUGH SUPPRESSANT THROAT DROPS');
insert into todos (user_id, todo) values (416, 'Wal Hist');
insert into todos (user_id, todo) values (214, 'Folic Acid');
insert into todos (user_id, todo) values (696, 'Nabumetone');
insert into todos (user_id, todo) values (696, 'DOLEX');
insert into todos (user_id, todo) values (647, 'REMERON');
insert into todos (user_id, todo) values (528, 'PrandiMet');
insert into todos (user_id, todo) values (749, 'Zolpidem Tartrate');
insert into todos (user_id, todo) values (56, 'Paroxetine');
insert into todos (user_id, todo) values (194, 'Doxycycline Hyclate');
insert into todos (user_id, todo) values (112, 'Degree Women Shower Clean');
insert into todos (user_id, todo) values (47, 'FeverALL Infants');
insert into todos (user_id, todo) values (854, 'enema mineral oil');
insert into todos (user_id, todo) values (877, 'Anti-Bacterial Deep Cleansing Hand');
insert into todos (user_id, todo) values (646, 'MEDICHOICE ANTICAVITY FLUORIDE');
insert into todos (user_id, todo) values (459, 'Food - Fish and Shellfish, Codfish Gadus callarias');
insert into todos (user_id, todo) values (493, 'Rabbitbush');
insert into todos (user_id, todo) values (846, 'COCHLIOBOLUS SATIVUS');
insert into todos (user_id, todo) values (123, 'Clario Ultra Blue Antibacterial Foaming Skin Cleanser');
insert into todos (user_id, todo) values (874, 'Ketoconazole');
insert into todos (user_id, todo) values (774, 'Prozac');
insert into todos (user_id, todo) values (178, 'Ultram ER');
insert into todos (user_id, todo) values (422, 'ENBREL');
insert into todos (user_id, todo) values (87, 'Oxygen');
insert into todos (user_id, todo) values (413, 'leader nite time cough');
insert into todos (user_id, todo) values (567, 'Clean and Clear Advantage Daily Soothing Acne Scrub');
insert into todos (user_id, todo) values (589, 'Shad Scale Pollen');
insert into todos (user_id, todo) values (510, 'Topco Associates LLC');
insert into todos (user_id, todo) values (412, 'Gabapentin');
insert into todos (user_id, todo) values (64, 'Hydroxyzine Hydrochloride');
insert into todos (user_id, todo) values (814, 'Mucinex');
insert into todos (user_id, todo) values (145, 'Antacid');
insert into todos (user_id, todo) values (164, 'Thyrotox');
insert into todos (user_id, todo) values (686, 'diltiazem hydrochloride');
insert into todos (user_id, todo) values (412, 'MYCAMINE');
insert into todos (user_id, todo) values (530, 'Nifedipine');
insert into todos (user_id, todo) values (235, 'Quetiapine Fumarate');
insert into todos (user_id, todo) values (613, 'Pollens - Trees, Oak Mix');
insert into todos (user_id, todo) values (360, 'Simvastatin');
insert into todos (user_id, todo) values (989, 'Zetia');
insert into todos (user_id, todo) values (575, 'Garnier');
insert into todos (user_id, todo) values (539, 'Caldolor');
insert into todos (user_id, todo) values (714, 'ESIKA');
insert into todos (user_id, todo) values (298, 'Nabumetone');
insert into todos (user_id, todo) values (173, 'Hydrochlorothiazide');
insert into todos (user_id, todo) values (601, 'Triamcinolone Acetonide');
insert into todos (user_id, todo) values (535, 'Koelers Grass Pollen');
insert into todos (user_id, todo) values (774, 'Nighttime Cold and Flu');
insert into todos (user_id, todo) values (898, 'acyclovir');
insert into todos (user_id, todo) values (884, 'AGRAPHIS NUTANS');
insert into todos (user_id, todo) values (696, 'Lisinopril');
insert into todos (user_id, todo) values (345, 'Naratriptan');
insert into todos (user_id, todo) values (537, 'Potassium Phosphates');
insert into todos (user_id, todo) values (570, 'Nitrogen');
insert into todos (user_id, todo) values (244, 'Banana Boat Mens');
insert into todos (user_id, todo) values (636, 'GONGJINHYANG SEOL WHITENING');
insert into todos (user_id, todo) values (776, 'ALTAVERA');
insert into todos (user_id, todo) values (666, 'ANTIBACTERIAL FOAMING');
insert into todos (user_id, todo) values (945, 'Glytone Clarifying SunVanish with Sunscreen');
insert into todos (user_id, todo) values (476, 'Walgreens');
insert into todos (user_id, todo) values (437, 'Neoral');
insert into todos (user_id, todo) values (50, 'LEVAQUIN');
insert into todos (user_id, todo) values (642, 'Sertraline');
insert into todos (user_id, todo) values (959, 'Pollens - Trees, Tree Mix 11');
insert into todos (user_id, todo) values (13, 'Neurontin');
insert into todos (user_id, todo) values (824, 'Treatment Set TS346964');
insert into todos (user_id, todo) values (266, 'Enoxaparin Sodium');
insert into todos (user_id, todo) values (292, 'Rohto Arctic');
insert into todos (user_id, todo) values (983, 'POTASSIUM CITRATE');
insert into todos (user_id, todo) values (308, 'Zometa');
insert into todos (user_id, todo) values (557, 'Bisoprolol Fumarate and Hydrochlorothiazide');
insert into todos (user_id, todo) values (87, 'Risperidone');
insert into todos (user_id, todo) values (888, 'Metoprolol Tartrate');
insert into todos (user_id, todo) values (994, 'Ready Foundation');
insert into todos (user_id, todo) values (461, 'IBS Irritable Bowel Syndrome Relief');
insert into todos (user_id, todo) values (773, 'UP AND UP ACID REDUCER');
insert into todos (user_id, todo) values (478, 'Theraproxen');
insert into todos (user_id, todo) values (553, 'Good Neighbor Pharmacy');
insert into todos (user_id, todo) values (223, 'Sunflower Seed');
insert into todos (user_id, todo) values (689, 'care one nasal');
insert into todos (user_id, todo) values (915, 'VIVITE Aftercare Environmental Protection Sunscreen SPF 30');
insert into todos (user_id, todo) values (103, 'Argentum Veratrum');
insert into todos (user_id, todo) values (869, 'Maybelline Dream Pure BB Beauty Balm');
insert into todos (user_id, todo) values (858, 'TAZORAC');
insert into todos (user_id, todo) values (164, 'Illusion Tinted Moisturizer Broad Spectrum Sand');
insert into todos (user_id, todo) values (345, 'Lexapro');
insert into todos (user_id, todo) values (667, 'Olanzapine');
insert into todos (user_id, todo) values (600, 'Gentiana Absinthium');
insert into todos (user_id, todo) values (374, 'NIACIN');
insert into todos (user_id, todo) values (939, 'Banana Boat Mens');
insert into todos (user_id, todo) values (632, 'BZK Pads');
insert into todos (user_id, todo) values (920, 'SelRx');
insert into todos (user_id, todo) values (706, 'Neo-Synephrine Cold and Sinus');
insert into todos (user_id, todo) values (554, 'Proctofoam');
insert into todos (user_id, todo) values (992, 'Intuniv');
insert into todos (user_id, todo) values (979, 'Amitriptyline Hydrochloride');
insert into todos (user_id, todo) values (424, 'XtraCare Foam Antibacterial Hand Wash');
insert into todos (user_id, todo) values (164, 'Happy Hands Foaming Hand Sanitizer');
insert into todos (user_id, todo) values (638, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into todos (user_id, todo) values (446, 'MiniDrops');
insert into todos (user_id, todo) values (431, 'Oxycodone and Acetaminophen');
insert into todos (user_id, todo) values (409, 'Phenylephrine Hydrochloride');
insert into todos (user_id, todo) values (978, 'THRULIFE EXTRA STRENGTH HEADACHE RELIEF');
insert into todos (user_id, todo) values (765, 'Trokendi XR');
insert into todos (user_id, todo) values (812, 'GUNA-FGF');
insert into todos (user_id, todo) values (749, 'Ropinirole Hydrochloride');
insert into todos (user_id, todo) values (148, 'Quetiapine Fumarate');
insert into todos (user_id, todo) values (761, 'Aromafields Jasmine Scented Antibacterial Hand Wash');
insert into todos (user_id, todo) values (345, 'Pollen Mix');
insert into todos (user_id, todo) values (927, 'Nifedipine');
insert into todos (user_id, todo) values (817, 'Diabecline');
insert into todos (user_id, todo) values (781, 'LOVASTATIN');
insert into todos (user_id, todo) values (52, 'Wakefern');
insert into todos (user_id, todo) values (468, 'Fenofibrate');
insert into todos (user_id, todo) values (162, 'good sense nighttime');
insert into todos (user_id, todo) values (683, 'DAILY DEFENCE SUNSCREEN Broad Spectrum SPF30');
insert into todos (user_id, todo) values (189, 'PANTOPRAZOLE SODIUM');
insert into todos (user_id, todo) values (316, 'Lovenox');
insert into todos (user_id, todo) values (231, 'Bactestat');
insert into todos (user_id, todo) values (330, 'Bio Rock Water');
insert into todos (user_id, todo) values (445, 'Tramadol Hydrchloride');
insert into todos (user_id, todo) values (950, 'AXIRON');
insert into todos (user_id, todo) values (757, 'Alpha-Caine');
insert into todos (user_id, todo) values (342, 'isosorbide mononitrate');
insert into todos (user_id, todo) values (557, 'Salmon');
insert into todos (user_id, todo) values (659, 'ALPRAZOLAM');
insert into todos (user_id, todo) values (616, 'CLINIMIX');
insert into todos (user_id, todo) values (202, 'SHISEIDO THE MAKEUP LIFTING FOUNDATION');
insert into todos (user_id, todo) values (159, 'Academy Sport');
insert into todos (user_id, todo) values (124, 'Bald Cypress');
insert into todos (user_id, todo) values (865, 'ALOE VESTA CLEAR BARRIER');
insert into todos (user_id, todo) values (787, 'Luminous AuraCapsule CC');
insert into todos (user_id, todo) values (371, 'Undecylenic Acid');
insert into todos (user_id, todo) values (206, 'Ibuprofen');
insert into todos (user_id, todo) values (768, 'Antibacterial Hand Problend');
insert into todos (user_id, todo) values (496, 'SparkleFresh');
insert into todos (user_id, todo) values (127, 'Atenolol');
insert into todos (user_id, todo) values (768, 'Old Spice Red Zone Sweat Defense');
insert into todos (user_id, todo) values (134, 'stila CC color correcting broad-spectrum SPF 20 03 TONE');
insert into todos (user_id, todo) values (860, 'SOLU-MEDROL');
insert into todos (user_id, todo) values (227, 'FOSINOPRIL Na');
insert into todos (user_id, todo) values (289, 'Aldex AN');
insert into todos (user_id, todo) values (823, 'Ideal Flawless');
insert into todos (user_id, todo) values (666, 'all day relief');
insert into todos (user_id, todo) values (223, 'Diltiazem Hydrochloride');
insert into todos (user_id, todo) values (358, 'RITE AID RENEWAL');
insert into todos (user_id, todo) values (541, 'Duetact');
insert into todos (user_id, todo) values (95, 'Hydromorphone Hydrochloride');
insert into todos (user_id, todo) values (244, 'Cymbalta');
insert into todos (user_id, todo) values (427, 'Clobetasol Propionate');
insert into todos (user_id, todo) values (963, 'lisinopril');
insert into todos (user_id, todo) values (608, 'Rite Aid');
insert into todos (user_id, todo) values (51, 'MVC-Fluoride');
insert into todos (user_id, todo) values (427, 'Degree Women Sheer Powder');
insert into todos (user_id, todo) values (281, 'Unisom SleepTabs');
insert into todos (user_id, todo) values (818, 'ZALEPLON');
insert into todos (user_id, todo) values (914, 'Oxalis Belladonna Special Order');
insert into todos (user_id, todo) values (434, 'Losartan Potassium and Hydrochlorothiazide');
insert into todos (user_id, todo) values (940, 'HAWAIIAN Tropic');
insert into todos (user_id, todo) values (531, 'FIRST AID RESEARCH ZINC OXYDE PLUS');
insert into todos (user_id, todo) values (845, 'Clearasil Daily Clear');
insert into todos (user_id, todo) values (904, 'Lisinopril and hydrochlorothiazide');
insert into todos (user_id, todo) values (425, 'Sertraline Hydrochloride');
insert into todos (user_id, todo) values (753, 'Oxygen');
insert into todos (user_id, todo) values (483, 'Wing Scale Pollen');
insert into todos (user_id, todo) values (12, 'Jet Lag RELIEF');
insert into todos (user_id, todo) values (766, 'Methimazole');
insert into todos (user_id, todo) values (989, 'Acetaminophen');
insert into todos (user_id, todo) values (991, 'VERELAN PM');
insert into todos (user_id, todo) values (978, 'ELF Clarifying Pressed');
insert into todos (user_id, todo) values (255, 'Lysol');
insert into todos (user_id, todo) values (765, 'Standardized Cat Hair');
insert into todos (user_id, todo) values (271, 'CVS Cold Sore Treatment');
insert into todos (user_id, todo) values (134, 'PROVENCE MAKEUP BASE');
insert into todos (user_id, todo) values (772, 'CONDITION AND ENHANCE SYSTEM');
insert into todos (user_id, todo) values (392, 'FixMySkin Healing Balm Fragrance-Free');
insert into todos (user_id, todo) values (219, 'ZYPREXA');
insert into todos (user_id, todo) values (737, 'Metoprolol Succinate');
insert into todos (user_id, todo) values (390, 'SaniFoam');
insert into todos (user_id, todo) values (798, 'Bone Strengthener');
insert into todos (user_id, todo) values (841, 'anti diarrheal');
insert into todos (user_id, todo) values (509, 'SIMETHICONE');
insert into todos (user_id, todo) values (949, 'Alprazolam');
insert into todos (user_id, todo) values (262, 'Xartemis');
insert into todos (user_id, todo) values (90, 'Belladonna and Opium');
insert into todos (user_id, todo) values (985, 'Medique Pain Off');
insert into todos (user_id, todo) values (687, 'Dysmenorrhea Diarrhea');
insert into todos (user_id, todo) values (294, 'butalbital, acetaminophen and caffeine');
insert into todos (user_id, todo) values (109, 'Infants Pain and Fever');
insert into todos (user_id, todo) values (147, 'Promethazine Hydrochloride');
insert into todos (user_id, todo) values (469, 'Ibuprofen');
insert into todos (user_id, todo) values (371, 'Morphine Sulfate');
insert into todos (user_id, todo) values (266, 'Clindamycin Hydrochloride');
insert into todos (user_id, todo) values (699, 'Immune Support');
insert into todos (user_id, todo) values (537, 'Fragmin');
insert into todos (user_id, todo) values (653, 'Testosterone Cypionate');
insert into todos (user_id, todo) values (770, 'RISPERIDONE');
insert into todos (user_id, todo) values (152, 'Pollens - Trees, Tree Mix 11');
insert into todos (user_id, todo) values (378, 'Lamotrigine');
insert into todos (user_id, todo) values (288, 'Atrovent');
insert into todos (user_id, todo) values (841, 'Enoxaparin Sodium');
insert into todos (user_id, todo) values (706, 'Lidocaine Hydrochloride and Hydrocortisone Acetate');
insert into todos (user_id, todo) values (184, 'Cranberry Spice Antibacterial Foaming Hand Wash');
insert into todos (user_id, todo) values (359, 'napoleon PERDIS SHEER GENIUS LIQUID FOUNDATION BROAD SPECTRUM SPF 20 Look 2');
insert into todos (user_id, todo) values (772, 'Day Time');
insert into todos (user_id, todo) values (14, 'Zebeta');
insert into todos (user_id, todo) values (572, 'Thyropar');
insert into todos (user_id, todo) values (601, 'risperidone');
insert into todos (user_id, todo) values (439, 'Acid Reducer');
insert into todos (user_id, todo) values (13, 'Latanoprost');
insert into todos (user_id, todo) values (143, 'Theophylline');
insert into todos (user_id, todo) values (191, 'mucus extended release');
insert into todos (user_id, todo) values (861, 'TONYMOLY My Sunny Perfecting Sun Block');
insert into todos (user_id, todo) values (869, 'Isoniazid');
insert into todos (user_id, todo) values (139, 'Allopurinol');
insert into todos (user_id, todo) values (330, 'NATURAL LEMON MINT HERB THROAT DROPS');
